import '../styles/globals.css'
import type { Metadata } from 'next'
import { Plus_Jakarta_Sans as PalusJakartaSnas } from 'next/font/google'

const inter = PalusJakartaSnas({ subsets: ['latin'], variable : "--font--sans" });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
